export function foodGenres() {
  return [
    {
      displayName: "American (new)",
      id: "newamerican",
      selected: false
    }, {
      displayName: "American (traditional)",
      id: "tradamerican",
      selected: false
    }, {
      displayName: "Afghan",
      id: "afghani",
      selected: false
    }, {
      displayName: "African",
      id: "african",
      selected: false
    }, {
      displayName: "Arabian",
      id: "arabian",
      selected: false
    }, {
      displayName: "Argentine",
      id: "argentine",
      selected: false
    }, {
      displayName: "Bangladeshi",
      id: "bangladeshi",
      selected: false
    }, {
      displayName: "Brazilian",
      id: "brazilian",
      selected: false
    }, {
      displayName: "British",
      id: "british",
      selected: false
    }, {
      displayName: "Burmese",
      id: "burmese",
      selected: false
    }, {
      displayName: "Cambodian",
      id: "cambodian",
      selected: false
    }, {
      displayName: "Caribbean",
      id: "caribbean",
      selected: false
    }, {
      displayName: "Chinese",
      id: "chinese",
      selected: false
    }, {
      displayName: "Szechuan",
      id: "szechuan",
      selected: false
    }, {
      displayName: "Cuban",
      id: "cuban",
      selected: false
    }, {
      displayName: "Filipino",
      id: "filipino",
      selected: false
    }, {
      displayName: "French",
      id: "french",
      selected: false
    }, {
      displayName: "German",
      id: "german",
      selected: false
    }, {
      displayName: "Greek",
      id: "greek",
      selected: false
    }, {
      displayName: "Indian",
      id: "indpak",
      selected: false
    }, {
      displayName: "Italian",
      id: "italian",
      selected: false
    }, {
      displayName: "Japanese",
      id: "japanese",
      selected: false
    }, {
      displayName: "Korean",
      id: "korean",
      selected: false
    }, {
      displayName: "Latin American",
      id: "latin",
      selected: false
    }, {
      displayName: "Malaysian",
      id: "malaysian",
      selected: false
    }, {
      displayName: "Mexican",
      id: "mexican",
      selected: false
    }, {
      displayName: "Portuguese",
      id: "portuguese",
      selected: false
    }, {
      displayName: "Taiwanese",
      id: "taiwanese",
      selected: false
    }, {
      displayName: "Thai",
      id: "thai",
      selected: false
    }, {
      displayName: "Turkish",
      id: "turkish",
      selected: false
    }, {
      displayName: "Vietnamese",
      id: "vietnamese",
      selected: false
    },
  ]
}

export function foodTypes() {
  return [
    {
      displayName: "bakeries",
      id: "bakeries",
      selected: false
    }, {
      displayName: "bars",
      id: "bars",
      selected: false
    }, {
      displayName: "bbq",
      id: "bbq",
      selected: false
    }, {
      displayName: "bento",
      id: "bento",
      selected: false
    }, {
      displayName: "breakfast and brunch",
      id: "breakfast_brunch",
      selected: false
    }, {
      displayName: "burgers",
      id: "burgers",
      selected: false
    }, {
      displayName: "cheesesteaks",
      id: "cheesesteaks",
      selected: false
    }, {
      displayName: "chicken wings",
      id: "chicken_wings",
      selected: false
    }, {
      displayName: "coffee",
      id: "coffee",
      selected: false
    }, {
      displayName: "desserts",
      id: "desserts",
      selected: false
    }, {
      displayName: "dim sum",
      id: "dimsum",
      selected: false
    }, {
      displayName: "diners",
      id: "diners",
      selected: false
    }, {
      displayName: "dumplings",
      id: "dumplings",
      selected: false
    }, {
      displayName: "fast food",
      id: "hot dogs",
      selected: false
    }, {
      displayName: "hotpot",
      id: "hotpot",
      selected: false
    }, {
      displayName: "ice cream",
      id: "icecream",
      selected: false
    }, {
      displayName: "pasta",
      id: "pastashops",
      selected: false
    }, {
      displayName: "poke",
      id: "poke",
      selected: false
    }, {
      displayName: "ramen",
      id: "ramen",
      selected: false
    }, {
      displayName: "kebab",
      id: "kebab",
      selected: false
    }, {
      displayName: "noodles",
      id: "noodles",
      selected: false
    }, {
      displayName: "pizza",
      id: "pizza",
      selected: false
    }, {
      displayName: "salad",
      id: "salad",
      selected: false
    }, {
      displayName: "seafood",
      id: "seafood",
      selected: false
    }, {
      displayName: "soup",
      id: "soup",
      selected: false
    }, {
      displayName: "steak",
      id: "steak",
      selected: false
    }, {
      displayName: "sushi",
      id: "sushi",
      selected: false
    }, {
      displayName: "vegan",
      id: "vegan",
      selected: false
    }, {
      displayName: "vegetarian",
      id: "vegetarian",
      selected: false
    }
  ]
}
